apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: extension-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-init
        image: postgres:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: extension-secrets
              key: DATABASE_PASSWORD
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              name: extension-config
              key: DATABASE_HOST
        - name: PGPORT
          valueFrom:
            configMapKeyRef:
              name: extension-config
              key: DATABASE_PORT
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: extension-config
              key: DATABASE_NAME
        - name: PGUSER
          value: "postgres"
        command:
        - sh
        - -c
        - |
          until pg_isready; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready. Running schema..."
          psql -f /schema/schema.sql
        volumeMounts:
        - name: schema
          mountPath: /schema
      volumes:
      - name: schema
        configMap:
          name: db-schema