apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard
  namespace: extension-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-dashboard
  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
      containers:
      - name: admin-dashboard
        image: node:18-alpine
        command: ["sh", "-c"]
        args: ["-c", "npm init -y && npm install express && echo 'const express = require(\"express\"); const app = express(); app.get(\"/\", (req,res) => res.send(\"<h1>Frontend Running</h1>\")); app.listen(3000, \"0.0.0.0\", () => console.log(\"Frontend ready\"));' > server.js && node server.js"]
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: extension-config
              key: NEXT_PUBLIC_API_URL
        - name: NEXT_PUBLIC_APP_URL
          valueFrom:
            configMapKeyRef:
              name: extension-config
              key: NEXT_PUBLIC_APP_URL
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: extension-system
spec:
  selector:
    app: admin-dashboard
  ports:
  - name: http
    port: 8081
    targetPort: 3000
  type: ClusterIP
