apiVersion: v1
kind: Namespace
metadata:
  name: master-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-portal
  namespace: master-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master-portal
  template:
    metadata:
      labels:
        app: master-portal
    spec:
      containers:
      - name: master-portal
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: portal-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: portal-content
        configMap:
          name: master-portal-html
---
apiVersion: v1
kind: Service
metadata:
  name: master-portal-service
  namespace: master-system
spec:
  selector:
    app: master-portal
  ports:
  - name: web
    port: 8090
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: master-portal-html
  namespace: master-system
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Master Portal - Enterprise Security System</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #0f172a; color: white; }
            .container { max-width: 1400px; margin: 0 auto; padding: 2rem; }
            .header { background: linear-gradient(135deg, #7c3aed, #a855f7); padding: 2rem; margin-bottom: 2rem; border-radius: 12px; }
            .nav { display: flex; gap: 1rem; margin-top: 1rem; }
            .nav-item { background: rgba(255,255,255,0.1); padding: 0.75rem 1.5rem; border-radius: 8px; cursor: pointer; transition: all 0.2s; }
            .nav-item:hover, .nav-item.active { background: rgba(255,255,255,0.2); }
            .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 2rem; margin-bottom: 2rem; }
            .card { background: #1e293b; padding: 2rem; border-radius: 12px; border: 1px solid #334155; }
            .btn { background: #7c3aed; color: white; padding: 0.75rem 1.5rem; border: none; border-radius: 8px; cursor: pointer; font-weight: 600; }
            .btn:hover { background: #6d28d9; }
            .btn-success { background: #10b981; }
            .btn-success:hover { background: #059669; }
            .form-group { margin-bottom: 1rem; }
            .form-group label { display: block; margin-bottom: 0.5rem; font-weight: 600; }
            .form-group input { width: 100%; padding: 0.75rem; border: 1px solid #475569; border-radius: 8px; background: #334155; color: white; }
            .modal { display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.8); z-index: 1000; }
            .modal-content { background: #1e293b; padding: 2rem; border-radius: 12px; max-width: 500px; margin: 10% auto; }
            .table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
            .table th, .table td { padding: 1rem; text-align: left; border-bottom: 1px solid #334155; }
            .table th { background: #334155; }
            .status { padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.8rem; font-weight: 600; }
            .status.active { background: #10b981; color: white; }
            .stat-number { font-size: 2.5rem; font-weight: bold; color: #7c3aed; }
            .stat-label { color: #94a3b8; margin-top: 0.5rem; }
            .section { display: none; }
            .section.active { display: block; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>👑 Master Portal</h1>
                <p>Root Administrative System - Enterprise Security</p>
                <div class="nav">
                    <div class="nav-item active" onclick="showSection('dashboard')">Dashboard</div>
                    <div class="nav-item" onclick="showSection('organizations')">Organizations</div>
                    <div class="nav-item" onclick="showSection('users')">All Users</div>
                    <div class="nav-item" onclick="showSection('extensions')">Extensions</div>
                </div>
            </div>

            <div id="dashboard" class="section active">
                <div class="grid">
                    <div class="card">
                        <h3>Organizations</h3>
                        <div class="stat-number" id="orgCount">2</div>
                        <div class="stat-label">Active Organizations</div>
                    </div>
                    <div class="card">
                        <h3>Total Users</h3>
                        <div class="stat-number" id="userCount">15</div>
                        <div class="stat-label">Across All Organizations</div>
                    </div>
                    <div class="card">
                        <h3>Extensions</h3>
                        <div class="stat-number">1</div>
                        <div class="stat-label">Deployed Extensions</div>
                    </div>
                    <div class="card">
                        <h3>System Status</h3>
                        <div class="stat-number" style="color: #10b981;">Online</div>
                        <div class="stat-label">All Services Running</div>
                    </div>
                </div>
            </div>

            <div id="organizations" class="section">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
                    <h2>Organizations Management</h2>
                    <button class="btn btn-success" onclick="showCreateOrgModal()">+ Create Organization</button>
                </div>
                <div class="card">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Organization</th>
                                <th>Domain</th>
                                <th>Admin Email</th>
                                <th>Users</th>
                                <th>Access Token</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody id="orgTableBody">
                            <tr>
                                <td>TechCorp Inc</td>
                                <td>techcorp.com</td>
                                <td>admin@techcorp.com</td>
                                <td>8/50</td>
                                <td><code>ext_abc123def456ghi789</code></td>
                                <td><span class="status active">Active</span></td>
                            </tr>
                            <tr>
                                <td>StartupXYZ</td>
                                <td>startupxyz.io</td>
                                <td>admin@startupxyz.io</td>
                                <td>7/25</td>
                                <td><code>ext_xyz789abc123def456</code></td>
                                <td><span class="status active">Active</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div id="users" class="section">
                <h2>All Users Management</h2>
                <div class="card">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Email</th>
                                <th>Organization</th>
                                <th>Role</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>John Admin</td>
                                <td>admin@techcorp.com</td>
                                <td>TechCorp Inc</td>
                                <td>org_admin</td>
                                <td><span class="status active">Active</span></td>
                            </tr>
                            <tr>
                                <td>Jane Employee</td>
                                <td>jane@techcorp.com</td>
                                <td>TechCorp Inc</td>
                                <td>user</td>
                                <td><span class="status active">Active</span></td>
                            </tr>
                            <tr>
                                <td>Mike Admin</td>
                                <td>admin@startupxyz.io</td>
                                <td>StartupXYZ</td>
                                <td>org_admin</td>
                                <td><span class="status active">Active</span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <div id="extensions" class="section">
                <h2>Extension Management</h2>
                <div class="card">
                    <h3>Browser Extension Deployment</h3>
                    <p style="margin: 1rem 0; color: #94a3b8;">Manage extension versions and organization access</p>
                    <div class="form-group">
                        <label>Extension Version</label>
                        <input type="text" value="v1.0.0" readonly>
                    </div>
                    <div class="form-group">
                        <label>Deployment Status</label>
                        <span class="status active">Active - All Organizations</span>
                    </div>
                    <button class="btn">Update Extension</button>
                </div>
            </div>
        </div>

        <!-- Create Organization Modal -->
        <div id="createOrgModal" class="modal">
            <div class="modal-content">
                <h3>Create New Organization</h3>
                <form id="createOrgForm">
                    <div class="form-group">
                        <label>Organization Name</label>
                        <input type="text" id="orgName" placeholder="Company Inc" required>
                    </div>
                    <div class="form-group">
                        <label>Domain</label>
                        <input type="text" id="orgDomain" placeholder="company.com" required>
                    </div>
                    <div class="form-group">
                        <label>Admin Email</label>
                        <input type="email" id="adminEmail" placeholder="admin@company.com" required>
                    </div>
                    <div class="form-group">
                        <label>User Limit</label>
                        <input type="number" id="userLimit" value="50" required>
                    </div>
                    <div style="display: flex; gap: 1rem; margin-top: 2rem;">
                        <button type="submit" class="btn btn-success">Create Organization</button>
                        <button type="button" class="btn" onclick="closeModal()">Cancel</button>
                    </div>
                </form>
            </div>
        </div>

        <script>
            function showSection(sectionId) {
                document.querySelectorAll('.section').forEach(s => s.classList.remove('active'));
                document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
                document.getElementById(sectionId).classList.add('active');
                event.target.classList.add('active');
            }

            function showCreateOrgModal() {
                document.getElementById('createOrgModal').style.display = 'block';
            }

            function closeModal() {
                document.getElementById('createOrgModal').style.display = 'none';
            }

            function generateToken() {
                return 'ext_' + Math.random().toString(36).substr(2, 16);
            }

            document.getElementById('createOrgForm').addEventListener('submit', function(e) {
                e.preventDefault();
                
                const name = document.getElementById('orgName').value;
                const domain = document.getElementById('orgDomain').value;
                const email = document.getElementById('adminEmail').value;
                const limit = document.getElementById('userLimit').value;
                const token = generateToken();
                
                const tbody = document.getElementById('orgTableBody');
                const row = tbody.insertRow();
                row.innerHTML = `
                    <td>${name}</td>
                    <td>${domain}</td>
                    <td>${email}</td>
                    <td>0/${limit}</td>
                    <td><code>${token}</code></td>
                    <td><span class="status active">Active</span></td>
                `;
                
                alert(`Organization created successfully!\n\nAccess Token: ${token}\n\nProvide this token to the Organization Admin for extension setup.`);
                
                closeModal();
                document.getElementById('createOrgForm').reset();
                
                // Update stats
                const orgCount = document.getElementById('orgCount');
                orgCount.textContent = parseInt(orgCount.textContent) + 1;
            });

            // Close modal when clicking outside
            window.onclick = function(event) {
                const modal = document.getElementById('createOrgModal');
                if (event.target == modal) {
                    closeModal();
                }
            }
        </script>
    </body>
    </html>